name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload artifacts
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifacts@v2
        with:
          name: Package
          path: staging
